#ifdef CT_AGA
  MOVE_PH(BPLCON3, BPLCON3_V),                // CL_PALETTE   Palette Colors AGA (bank 0)
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  #if CLP_DEPTH > 1
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  #if CLP_DEPTH > 2
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  #if CLP_DEPTH > 3
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  #if CLP_DEPTH > 4
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  #if CLP_DEPTH > 5
  MOVE(BPLCON3, BPLCON3_V | (1 << 13)),       //              bank 1
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  #if CLP_DEPTH > 6
  MOVE(BPLCON3, BPLCON3_V | (2 << 13)),       //              bank 2
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  MOVE(BPLCON3, BPLCON3_V | (3 << 13)),       //              bank 3
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  MOVE(BPLCON3, BPLCON3_V | (4 << 13)),       //              bank 4
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  #if CLP_DEPTH > 7
  MOVE(BPLCON3, BPLCON3_V | (5 << 13)),       //              bank 5
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  MOVE(BPLCON3, BPLCON3_V | (6 << 13)),       //              bank 6
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  MOVE(BPLCON3, BPLCON3_V | (7 << 13)),       //              bank 7
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  #endif // CLP_DEPTH > 7
  #endif // CLP_DEPTH > 6
  #endif // CLP_DEPTH > 5
  #endif // CLP_DEPTH > 4
  #endif // CLP_DEPTH > 3
  #endif // CLP_DEPTH > 2
  #endif // CLP_DEPTH > 1
  MOVE(BPLCON3, BPLCON3_V | BPLCON3_LOCT),    //              bank 0 LOCT
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  #if CLP_DEPTH > 1
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  #if CLP_DEPTH > 2
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  #if CLP_DEPTH > 3
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  #if CLP_DEPTH > 4
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  #if CLP_DEPTH > 5
  MOVE(BPLCON3, BPLCON3_V | BPLCON3_LOCT | (1 << 13)), //     bank 1 LOCT
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  #if CLP_DEPTH > 6
  MOVE(BPLCON3, BPLCON3_V | BPLCON3_LOCT | (2 << 13)), //     bank 2 LOCT
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  MOVE(BPLCON3, BPLCON3_V | BPLCON3_LOCT | (3 << 13)), //     bank 3 LOCT
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  MOVE(BPLCON3, BPLCON3_V | BPLCON3_LOCT | (4 << 13)), //     bank 4 LOCT
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  #if CLP_DEPTH > 7
  MOVE(BPLCON3, BPLCON3_V | BPLCON3_LOCT | (5 << 13)), //     bank 5 LOCT
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  MOVE(BPLCON3, BPLCON3_V | BPLCON3_LOCT | (6 << 13)), //     bank 6 LOCT
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  MOVE(BPLCON3, BPLCON3_V | BPLCON3_LOCT | (7 << 13)), //     bank 7 LOCT
  MOVE(COLOR00, 0x0),                         //
  MOVE(COLOR01, 0x0),                         //
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  #endif // CLP_DEPTH > 7
  #endif // CLP_DEPTH > 6
  #endif // CLP_DEPTH > 5
  #endif // CLP_DEPTH > 4
  #endif // CLP_DEPTH > 3
  #endif // CLP_DEPTH > 2
  #endif // CLP_DEPTH > 1
#else // CT_AGA
  MOVE_PH(COLOR00, 0x0),                      // CL_PALETTE   Palette Colors OCS/ECS
  MOVE(COLOR01, 0x0),                         //
  #if CLP_DEPTH > 1
  MOVE(COLOR02, 0x0),                         //
  MOVE(COLOR03, 0x0),                         //
  #if CLP_DEPTH > 2
  MOVE(COLOR04, 0x0),                         //
  MOVE(COLOR05, 0x0),                         //
  MOVE(COLOR06, 0x0),                         //
  MOVE(COLOR07, 0x0),                         //
  #if CLP_DEPTH > 3
  MOVE(COLOR08, 0x0),                         //
  MOVE(COLOR09, 0x0),                         //
  MOVE(COLOR10, 0x0),                         //
  MOVE(COLOR11, 0x0),                         //
  MOVE(COLOR12, 0x0),                         //
  MOVE(COLOR13, 0x0),                         //
  MOVE(COLOR14, 0x0),                         //
  MOVE(COLOR15, 0x0),                         //
  #if CLP_DEPTH > 4
  MOVE(COLOR16, 0x0),                         //
  MOVE(COLOR17, 0x0),                         //
  MOVE(COLOR18, 0x0),                         //
  MOVE(COLOR19, 0x0),                         //
  MOVE(COLOR20, 0x0),                         //
  MOVE(COLOR21, 0x0),                         //
  MOVE(COLOR22, 0x0),                         //
  MOVE(COLOR23, 0x0),                         //
  MOVE(COLOR24, 0x0),                         //
  MOVE(COLOR25, 0x0),                         //
  MOVE(COLOR26, 0x0),                         //
  MOVE(COLOR27, 0x0),                         //
  MOVE(COLOR28, 0x0),                         //
  MOVE(COLOR29, 0x0),                         //
  MOVE(COLOR30, 0x0),                         //
  MOVE(COLOR31, 0x0),                         //
  #endif // CLP_DEPTH > 4
  #endif // CLP_DEPTH > 3
  #endif // CLP_DEPTH > 2
  #endif // CLP_DEPTH > 1
#endif //CT_AGA
